/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tosirom.practica.ui;

/**
 *
 * @author nguyen
 */
public class MainFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame2
     */
    public MainFrame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        formAngajati1 = new com.tosirom.practica.ui.panels.FormAngajati();
        formCamere1 = new com.tosirom.practica.ui.panels.FormCamere();
        formClienti1 = new com.tosirom.practica.ui.panels.FormClienti();
        formInchirieri1 = new com.tosirom.practica.ui.panels.FormInchirieri();
        formInventarCamera1 = new com.tosirom.practica.ui.panels.FormInventarCamera();
        formPlati1 = new com.tosirom.practica.ui.panels.FormPlati();
        formProduse1 = new com.tosirom.practica.ui.panels.FormProduse();
        formVehicule1 = new com.tosirom.practica.ui.panels.FormVehicule();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addTab("Angajati", formAngajati1);
        jTabbedPane1.addTab("Camere", formCamere1);
        jTabbedPane1.addTab("Clienti", formClienti1);
        jTabbedPane1.addTab("Inchirieri", formInchirieri1);
        jTabbedPane1.addTab("InvetarCamera", formInventarCamera1);

        javax.swing.GroupLayout formPlati1Layout = new javax.swing.GroupLayout(formPlati1);
        formPlati1.setLayout(formPlati1Layout);
        formPlati1Layout.setHorizontalGroup(
            formPlati1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );
        formPlati1Layout.setVerticalGroup(
            formPlati1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Plati", formPlati1);
        jTabbedPane1.addTab("Produse", formProduse1);
        jTabbedPane1.addTab("Vehicule", formVehicule1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.tosirom.practica.ui.panels.FormAngajati formAngajati1;
    private com.tosirom.practica.ui.panels.FormCamere formCamere1;
    private com.tosirom.practica.ui.panels.FormClienti formClienti1;
    private com.tosirom.practica.ui.panels.FormInchirieri formInchirieri1;
    private com.tosirom.practica.ui.panels.FormInventarCamera formInventarCamera1;
    private com.tosirom.practica.ui.panels.FormPlati formPlati1;
    private com.tosirom.practica.ui.panels.FormProduse formProduse1;
    private com.tosirom.practica.ui.panels.FormVehicule formVehicule1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
