/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tosirom.practica.ui.panels;

import com.tosirom.practica.database.Database;
import com.tosirom.practica.database.Inchirieri;
import com.tosirom.practica.models.InchirieriTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.sql.Date;
import javax.swing.RowSorter;

/**
 *
 
 */
public class FormInchirieri extends javax.swing.JPanel {

    /**
     * Creates new form FormInchirieri
     */
    public FormInchirieri() {
        initComponents();
        RefreshInchirieriTable();
        
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(tabelInchirieri.getModel());
        tabelInchirieri.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRefresh = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelInchirieri = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbClienti = new javax.swing.JComboBox<>();
        cmbProdus = new javax.swing.JComboBox<>();
        dateInchiriere = new com.toedter.calendar.JDateChooser();
        dateReturnare = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        chkReturnat = new javax.swing.JCheckBox();
        btnChange = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        btnRefresh.setText("Refresh");
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
        });
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete selected row");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tabelInchirieri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nume", "Prenume", "Adresa", "Telefon", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tabelInchirieri);

        jLabel2.setText("ID Client");

        jLabel3.setText("ID Produs");

        jLabel4.setText("Data Inchiriere");

        cmbClienti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbProdus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Data Returnare");

        chkReturnat.setText("Returnat");

        btnChange.setText("Creeaza / Actualizeaza");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkReturnat)
                            .addComponent(dateReturnare, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbClienti, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbProdus, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateInchiriere, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbClienti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProdus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateInchiriere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateReturnare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkReturnat)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnDelete)
                    .addComponent(btnChange)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         InchirieriTableModel model = (InchirieriTableModel) tabelInchirieri.getModel();

        int[] selRows = tabelInchirieri.getSelectedRows();

        for(int i = 0; i < selRows.length; i++) {
            Inchirieri.DeleteInchirieri((Integer)model.getValueAt(selRows[i], 0));
        }

        RefreshInchirieriTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void resetForm() {
        cmbClienti.setSelectedIndex(0);
        cmbProdus.setSelectedIndex(0);
        dateInchiriere.setDate(new Date(System.currentTimeMillis()));
        dateReturnare.setDate(new Date(System.currentTimeMillis()));
        chkReturnat.setSelected(false);
    }
    
    private void populateDropdowns() {
         try(Connection conn = Database.getConnection()) {
            String SQL_clienti = "SELECT ID FROM Clienti";
            Statement statement = conn.createStatement();
            ResultSet result = statement.executeQuery(SQL_clienti);
            
            cmbClienti.removeAllItems();
            while (result.next()) {
                Integer id = result.getInt("ID");
                cmbClienti.addItem(id.toString());
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
         
         try(Connection conn = Database.getConnection()) {
            String SQL_clienti = "SELECT ID FROM Produse";
            Statement statement = conn.createStatement();
            ResultSet result = statement.executeQuery(SQL_clienti);
            
            cmbProdus.removeAllItems();
            while (result.next()) {
                Integer id = result.getInt("ID");
                cmbProdus.addItem(id.toString());
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        resetForm();
        populateDropdowns();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        Inchirieri i = new Inchirieri();
        
        i.ID_Client = Integer.parseInt((String)cmbClienti.getSelectedItem());
        i.ID_Produs = Integer.parseInt((String)cmbProdus.getSelectedItem());
        i.Data_inchiriere = new Date(dateInchiriere.getDate().getTime());
        i.Data_returnare = new Date(dateReturnare.getDate().getTime());
        i.Returnat = chkReturnat.isSelected();
        
        if(Inchirieri.CreateInchirieri(i)) {
            resetForm();
        }
        RefreshInchirieriTable();
    }//GEN-LAST:event_btnChangeActionPerformed

        private void RefreshInchirieriTable() {
        populateDropdowns();
        InchirieriTableModel model = new InchirieriTableModel();
        tabelInchirieri.setModel(model);
        
          
        var inchirieri = Inchirieri.GetAllInchirieri();
        
        RowSorter<?> sorter = tabelInchirieri.getRowSorter();
        tabelInchirieri.setAutoCreateRowSorter(false);
        tabelInchirieri.setRowSorter(null);
        
        for(int i = 0; i < inchirieri.size(); i++) {
            
            model.add(inchirieri.get(i));
        }
        
        tabelInchirieri.setRowSorter((RowSorter<? extends TableModel>) sorter);
        tabelInchirieri.setAutoCreateRowSorter(true);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox chkReturnat;
    private javax.swing.JComboBox<String> cmbClienti;
    private javax.swing.JComboBox<String> cmbProdus;
    private com.toedter.calendar.JDateChooser dateInchiriere;
    private com.toedter.calendar.JDateChooser dateReturnare;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tabelInchirieri;
    // End of variables declaration//GEN-END:variables
}
